version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:8.3
    working_dir: /var/www/html
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html # Non Mac users.
      # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
    environment:
      XDEBUG_CONFIG: "client_host=172.17.0.1" # Non-Mac users.
      # XDEBUG_CONFIG: "client_host=host.docker.internal" # Mac users.
      # Do not use xdebug develop mode causing transaction timing issues.
      # @see https://www.drupal.org/project/drupal/issues/3405976
      XDEBUG_MODE: "debug"
      PHP_IDE_CONFIG: "serverName=Docker"
      # Enable step debugging for all PHP request. See ./README.md#step-debugging for more information.
      # XDEBUG_SESSION: 1
  mysql:
    image: percona/percona-server:8.0
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3 --skip-log-bin --innodb-flush-log-at-trx-commit=2 --innodb-read-io-threads=16 --innodb-write-io-threads=16
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # ports:
    #   - 3306:3306
  selenium:
    image: selenium/standalone-chrome:4.1.3
    environment:
      - DISPLAY=:99
      - VNC_NO_PASSWORD=1
    ports:
      - '5900:5900'
    expose:
      - '4444'
    shm_size: 2g
  node:
    image: node:18.12.0
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV-''}
      - SHELL=bash
    volumes:
      - ./:/home/node/app
    command: "sleep infinity"

#### Mac users: uncomment the "volumes" key to enable the NFS file sharing. You can find more information about Docker for Mac here: https://github.com/openeuropa/openeuropa/blob/master/docs/starting/tooling.md#using-docker-on-macos

#volumes:
#  nfsmount:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#      device: ":${PWD}/"

#### End Mac users.
